version: '3.3'
volumes:
  foodgram_static:
  foodgram_media:
  foodgram_db:
  foodgram_frontend:

services:
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - foodgram_db:/var/lib/postgresql/data/

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - foodgram_static:/app/static_backend
      - foodgram_media:/app/media
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static_backend/
      - foodgram_media:/var/html/media/
    depends_on:
      - backend
