version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: flegmatik/foodgram_backend:latest
    volumes:
      - foodgram_static:/app/static_backend/
      - foodgram_media:/app/media/
      - redoc:/app/api/docs
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: flegmatik/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static_backend/
      - foodgram_media:/var/html/media/
    depends_on:
      - backend
    restart: always

volumes:
  foodgram_static:
  foodgram_media:
  foodgram_db:
  redoc:
